name: CI

on:
  push:
    branches:
      - master
  pull_request:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  RUST_VERSION: 1.73.0

jobs:
  lint-toml-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}

      - name: Install Cargo.toml linter
        uses: baptiste0928/cargo-install@v2
        with:
          crate: cargo-toml-lint
          version: "0.1.1"

      - name: Run Cargo.toml linter
        run: git ls-files | grep Cargo.toml$ | xargs --verbose -n 1 cargo-toml-lint

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          [
            "metamask-predicate",
            "metamask-script",
          ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: clippy, rustfmt

      - name: Init cache
        uses: Swatinem/rust-cache@v2

      - name: Install Fuel toolchain
        uses: FuelLabs/action-fuel-toolchain@v0.6.0
        with:
          toolchain: latest
          date: 2023-09-29

      - name: Check Sway formatting
        run: |
          cd ${{ matrix.project }}
          forc fmt --check

      - name: Check Rust formatting
        run: |
          cd ${{ matrix.project }}
          cargo fmt --verbose --check

      - name: Build Sway
        run: |
          cd ${{ matrix.project }}
          forc build

      - name: Build Rust files
        run: |
          cd ${{ matrix.project }}
          cargo build

      - name: Check Clippy Linter
        run: |
          cd ${{ matrix.project }}
          cargo clippy --all-features --all-targets -- -D warnings

      - name: Run Rust tests
        run: |
          cd ${{ matrix.project }}
          cargo test
